name: Pipeline docker image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u alefh --password-stdin

      - name: Build the version of app
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:5})

      - name: Build the tagged Vote Docker image
        run: cd desafio-voting-app/vote && docker build -t alefh/vote_docker9399:${{steps.vars.outputs.tag}} .

      - name: Push the tagged Vote Docker image
        run: docker push alefh/vote_docker9399:${{steps.vars.outputs.tag}}

      - name: Build the latest Vote Docker image
        run: cd desafio-voting-app/vote && docker build -t alefh/vote_docker9399:latest .

      - name: Push the latest Vote Docker image
        run: docker push alefh/vote_docker9399:latest
